using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Noggog;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using System.IO;
using System.Threading.Tasks;
using System;

namespace Translator
{
    public class Program
    {
        static Lazy<Settings> Settings = null!;
        static int i = 0;
        static bool verboseLog = false;

        public static Task<int> Main(string[] args)
        {
            return SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "Translator.esp")
                .Run(args);
        }
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var translationDir = Settings.Value.translationDir;
            verboseLog = Settings.Value.verboseLog;
            if (translationDir == "")
            {
                Console.WriteLine("Error: Translation Dir must be a valid directory!");
                return;
            }
            foreach(String file in Directory.GetFiles(translationDir))
            {
                if (Path.GetExtension(file) == ".esp")
                {
                    espCopy(file);
                } else
                {
                    Console.WriteLine(file + " is not an esp!");
                }
            }

            //copy stuff that need to be translated into Synthesis.esp
            //condition check:
            //iff stuff with corresponding formID doens't exist, skip it.
            void espCopy(String espPath)
            {

                Console.WriteLine("processing translation from " + espPath);
                using var esp = SkyrimMod.CreateFromBinaryOverlay(espPath, SkyrimRelease.SkyrimSE);
                foreach (var _rec in esp.Weapons)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<IWeaponGetter>(key, out var rec) && _rec.Name != null)
                    {
                        var tranPatch = state.PatchMod.Weapons.GetOrAddAsOverride(rec);
                        tranPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }
                foreach(var _rec in esp.Armors)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<IArmorGetter>(key, out var rec) && _rec.Name != null)
                    {
                        var tranPatch = state.PatchMod.Armors.GetOrAddAsOverride(rec);
                        tranPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }
                foreach(var _rec in esp.Ingredients)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<IIngredientGetter>(key, out var rec) && _rec.Name != null)
                    { 
                        var transPatch = state.PatchMod.Ingredients.GetOrAddAsOverride(rec);
                        transPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }
                foreach (var _rec in esp.Npcs)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<INpcGetter>(key, out var rec) && _rec.Name != null)
                    {
                        var transPatch = state.PatchMod.Npcs.GetOrAddAsOverride(rec);
                        transPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }
                foreach (var _rec in esp.Worldspaces)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<IWorldspaceGetter>(key, out var rec) && _rec.Name != null)
                    {
                        var transPatch = state.PatchMod.Worldspaces.GetOrAddAsOverride(rec);
                        transPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }
                foreach (var _rec in esp.MagicEffects)
                {
                    FormKey key = _rec.FormKey;
                    if (state.LinkCache.TryResolve<IMagicEffectGetter>(key, out var rec) && _rec.Name != null)
                    {
                        var transPatch = state.PatchMod.MagicEffects.GetOrAddAsOverride(rec);
                        transPatch.Name = _rec.Name.ToString();
                        i++;
                        if (verboseLog)
                        {
                            Console.WriteLine($"translated {rec.Name}");
                        }
                    }
                }

                //state.LoadOrder.PriorityOrder.SkyrimMajorRecord().WinningContextOverrides(state.LinkCache).ForEach(obj =>
                //{
                    //var record = obj.Record;
                    //if (record is IWeaponGetter item && item.FormKey)
                //});


            }



            System.Console.WriteLine("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");


            uint count = 0;
                // For every Npc that exists
            foreach (var npc in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                // For every Npc group in our target mods, in order
                //Console.WriteLine("NPC NAME: " + npc.Name);
            }
            foreach (var worldSpace in state.LoadOrder.PriorityOrder.Worldspace().WinningOverrides())
            {
                //var worldCopy = worldSpace.DeepCopy();
                //Console.WriteLine(worldCopy.Name);
            }
            foreach (var weapon in state.LoadOrder.PriorityOrder.Weapon().WinningOverrides())
            {
                //var weaponCopy = weapon.DeepCopy();
                //Console.WriteLine(weaponCopy.Name);
            }

            System.Console.WriteLine($"Translated {i} records.");
        }
    }
}
